spring:
  datasource:
    url: ${PG_DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

cj-dropshipping:
  api:
    url: ${CJ_BASE_URL}
    key: ${CJ_API_KEY}

logging:
  level:
    root: INFO