-- =============================================
-- Seed data: 25 brands (idempotent)
-- =============================================

INSERT INTO brands (id, name, slug, logo_url, website_url, description, status, created_at)
VALUES
    ('seed-brand-apple',       'Apple',         'apple',         'https://www.google.com/s2/favicons?domain=apple.com&sz=128',         'https://www.apple.com',         'Tecnología, innovación y diseño premium',                              'ACTIVE', NOW()),
    ('seed-brand-samsung',     'Samsung',       'samsung',       'https://www.google.com/s2/favicons?domain=samsung.com&sz=128',       'https://www.samsung.com',       'Electrónica de consumo y semiconductores',                             'ACTIVE', NOW()),
    ('seed-brand-sony',        'Sony',          'sony',          'https://www.google.com/s2/favicons?domain=sony.com&sz=128',          'https://www.sony.com',          'Entretenimiento, gaming y electrónica',                                'ACTIVE', NOW()),
    ('seed-brand-lg',          'LG',            'lg',            'https://www.google.com/s2/favicons?domain=lg.com&sz=128',            'https://www.lg.com',            'Electrodomésticos y electrónica',                                      'ACTIVE', NOW()),
    ('seed-brand-nike',        'Nike',          'nike',          'https://www.google.com/s2/favicons?domain=nike.com&sz=128',          'https://www.nike.com',          'Calzado y ropa deportiva de alto rendimiento',                         'ACTIVE', NOW()),
    ('seed-brand-adidas',      'Adidas',        'adidas',        'https://www.google.com/s2/favicons?domain=adidas.com&sz=128',        'https://www.adidas.com',        'Ropa, calzado y equipamiento deportivo',                               'ACTIVE', NOW()),
    ('seed-brand-bose',        'Bose',          'bose',          'https://www.google.com/s2/favicons?domain=bose.com&sz=128',          'https://www.bose.com',          'Audio de alta calidad y sistemas de sonido',                           'ACTIVE', NOW()),
    ('seed-brand-jbl',         'JBL',           'jbl',           'https://www.google.com/s2/favicons?domain=jbl.com&sz=128',           'https://www.jbl.com',           'Altavoces, auriculares y audio profesional',                           'ACTIVE', NOW()),
    ('seed-brand-logitech',    'Logitech',      'logitech',      'https://www.google.com/s2/favicons?domain=logitech.com&sz=128',      'https://www.logitech.com',      'Periféricos, webcams y accesorios de PC',                              'ACTIVE', NOW()),
    ('seed-brand-razer',       'Razer',         'razer',         'https://www.google.com/s2/favicons?domain=razer.com&sz=128',         'https://www.razer.com',         'Periféricos y portátiles para gaming',                                 'ACTIVE', NOW()),
    ('seed-brand-dyson',       'Dyson',         'dyson',         'https://www.google.com/s2/favicons?domain=dyson.com&sz=128',         'https://www.dyson.com',         'Aspiradoras, ventiladores y cuidado del cabello',                      'ACTIVE', NOW()),
    ('seed-brand-philips',     'Philips',       'philips',       'https://www.google.com/s2/favicons?domain=philips.com&sz=128',       'https://www.philips.com',       'Iluminación, salud y bienestar',                                       'ACTIVE', NOW()),
    ('seed-brand-bosch',       'Bosch',         'bosch',         'https://www.google.com/s2/favicons?domain=bosch.com&sz=128',         'https://www.bosch.com',         'Herramientas eléctricas y electrodomésticos',                          'ACTIVE', NOW()),
    ('seed-brand-dell',        'Dell',          'dell',          'https://www.google.com/s2/favicons?domain=dell.com&sz=128',          'https://www.dell.com',          'Computadoras, servidores y soluciones empresariales',                  'ACTIVE', NOW()),
    ('seed-brand-hp',          'HP',            'hp',            'https://www.google.com/s2/favicons?domain=hp.com&sz=128',            'https://www.hp.com',            'Computadoras personales e impresoras',                                 'ACTIVE', NOW()),
    ('seed-brand-lenovo',      'Lenovo',        'lenovo',        'https://www.google.com/s2/favicons?domain=lenovo.com&sz=128',        'https://www.lenovo.com',        'Portátiles, PCs y soluciones inteligentes',                            'ACTIVE', NOW()),
    ('seed-brand-microsoft',   'Microsoft',     'microsoft',     'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128',     'https://www.microsoft.com',     'Software, hardware y servicios en la nube',                            'ACTIVE', NOW()),
    ('seed-brand-canon',       'Canon',         'canon',         'https://www.google.com/s2/favicons?domain=canon.com&sz=128',         'https://www.canon.com',         'Cámaras, impresoras y equipos ópticos',                                'ACTIVE', NOW()),
    ('seed-brand-gopro',       'GoPro',         'gopro',         'https://www.google.com/s2/favicons?domain=gopro.com&sz=128',         'https://www.gopro.com',         'Cámaras de acción y accesorios',                                       'ACTIVE', NOW()),
    ('seed-brand-xiaomi',      'Xiaomi',        'xiaomi',        'https://www.google.com/s2/favicons?domain=xiaomi.com&sz=128',        'https://www.xiaomi.com',        'Smartphones, wearables y dispositivos inteligentes',                   'ACTIVE', NOW()),
    ('seed-brand-puma',        'Puma',          'puma',          'https://www.google.com/s2/favicons?domain=puma.com&sz=128',          'https://www.puma.com',          'Calzado y ropa deportiva con estilo urbano',                           'ACTIVE', NOW()),
    ('seed-brand-northface',   'The North Face','the-north-face','https://www.google.com/s2/favicons?domain=thenorthface.com&sz=128',  'https://www.thenorthface.com',  'Ropa y equipamiento para actividades al aire libre',                   'ACTIVE', NOW()),
    ('seed-brand-kitchenaid',  'KitchenAid',    'kitchenaid',    'https://www.google.com/s2/favicons?domain=kitchenaid.com&sz=128',    'https://www.kitchenaid.com',    'Electrodomésticos de cocina premium',                                  'ACTIVE', NOW()),
    ('seed-brand-lego',        'LEGO',          'lego',          'https://www.google.com/s2/favicons?domain=lego.com&sz=128',          'https://www.lego.com',          'Juguetes de construcción creativos para todas las edades',             'ACTIVE', NOW()),
    ('seed-brand-generic',     'Genérica',      'generica',      NULL,                                          NULL,                            'Marca genérica para productos sin marca definida',                     'INACTIVE', NOW())
ON CONFLICT (id) DO NOTHING;
